name: Deploy Web App to GitHub Pages

on:
  push:
    branches:
      - main # Trigger on push to main branch

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Build Web App
        run: ./gradlew :webApp:composeCompatibilityBrowserDistribution

      - name: Copy build to docs
        run: |
          mkdir -p docs
          cp -r webApp/build/dist/composeCompatibility/productionExecutable/* docs/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the docs directory
          path: 'docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
